name: dodact_v1
description: Sanatçı ruhların buluşma noktası.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  provider: ^6.0.2
  intl: ^0.17.0


  #FIREBASE
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  firebase_crashlytics: ^2.4.5
  cloud_firestore: ^3.1.6
  firebase_messaging: ^11.2.5
  #google_mobile_ads: ^0.13.0
  cloud_functions: ^3.2.5
  firebase_remote_config: ^1.0.4
  firebase_dynamic_links: ^3.0.1
  
  google_sign_in: ^5.2.2
  sign_in_with_apple: ^3.3.0
  crypto: ^3.0.1
  get_it: ^7.2.0

  file_picker: ^4.3.1
  curved_navigation_bar: ^1.0.1
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.4+4
  introduction_screen: ^2.1.0
  youtube_player_flutter: ^8.0.0

  flutter_vector_icons: ^1.0.0
  cool_alert: ^1.1.0
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.3.0
  getwidget: ^2.0.3
  url_launcher: ^6.0.18
  # geolocator: 7.6.2

  flutter_native_splash: ^1.2.0
  shared_preferences: ^2.0.12
  flutter_staggered_grid_view: ^0.4.0

  flutter_image_compress: ^1.1.0
  path_provider: ^2.0.8
  flutter_linkify: ^5.0.2
  flutter_slidable: ^0.6.0
  photo_view: ^0.12.0
  pinch_zoom: ^1.0.0
  cached_network_image: ^3.2.0
  logger: ^1.1.0
  google_fonts: ^2.1.0
  flutter_bounce: ^1.1.0
  google_maps_flutter: ^2.1.1
  share_plus: ^3.0.4
  just_audio: ^0.9.18
  qr_flutter: ^4.0.0
  profanity_filter: ^2.0.0
  circular_menu: ^1.2.3
  awesome_notifications: ^0.6.20
  easy_localization: ^3.0.0
  paginate_firestore: ^1.0.3
  package_info_plus: ^1.3.0
  multi_select_flutter: ^4.0.0
  youtube_metadata: ^1.0.1
  flutter_blurhash: ^0.6.0
  permission_handler: ^8.2.6
  google_maps_place_picker_mb: ^2.0.0-mb.9
  google_maps_webservice: ^0.0.20-nullsafety.5
  geolocator: ^7.7.1
  image_cropper: ^1.4.1
  flutter_svg: ^1.0.0
  syncfusion_flutter_pdfviewer: ^19.4.42-beta
  readmore: ^2.1.0
  get: ^4.6.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app/logo.png"
  remove_alpha_ios: true


#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/
    - assets/images/application_page/
    - assets/images/app/
    - assets/images/app/interests/
    - assets/images/app/situations/
    - assets/images/onboarding/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Medium.otf
          weight: 400
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Regular.otf
          weight: 500
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Bold.otf
          weight: 700
