name: dodact_v1
description: Sanatçı ruhların buluşma noktası.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  provider: ^5.0.0
  intl: ^0.17.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.0
  google_sign_in: ^5.0.1
  get_it: ^6.0.0
  firebase_storage: ^8.0.1
  file_picker: ^3.0.1
  curved_navigation_bar: ^0.3.7
  flutter_spinkit: ^5.0.0
  image_picker: ^0.7.4
  multi_image_picker: ^4.8.0
  introduction_screen: ^2.1.0
  youtube_player_flutter: ^8.0.0
  #TODO: buradan diğer navbarı sil

  flutter_vector_icons: ^1.0.0
  cool_alert: ^1.0.3
  horizontal_card_pager: ^1.1.1
  flutter_form_builder: "^6.0.0-nullsafety.1"
  getwidget: ^1.2.4
  url_launcher: ^6.0.9
  story_view: ^0.12.8
  path_provider: ^2.0.1
  firebase_messaging: ^10.0.3
  flutter_native_splash: ^1.2.0
  shared_preferences: ^2.0.6
  flutter_material_pickers: ^3.1.0
  ff_navigation_bar:
    git:
      url: https://github.com/ozyildirim/Flutter-FFNavigationBar
  flutter_staggered_grid_view: ^0.4.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/creation/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
