name: dodact_v1
description: Sanatçı ruhların buluşma noktası.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.8+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0

  provider: ^6.0.1
  intl: ^0.17.0


  #FIREBASE
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  firebase_storage: ^10.1.0
  firebase_crashlytics: ^2.3.0
  cloud_firestore: ^3.1.0
  firebase_messaging: ^11.1.0
  #google_mobile_ads: ^0.13.0
  cloud_functions: ^3.1.1
  firebase_remote_config: ^0.11.0+2
  firebase_dynamic_links: ^3.0.1
  
  google_sign_in: ^5.0.7
  sign_in_with_apple: ^3.2.0
  crypto: ^3.0.1
  get_it: ^7.2.0

  file_picker: ^4.2.7
  curved_navigation_bar: ^1.0.1
  flutter_spinkit: ^5.0.0
  image_picker: ^0.8.3
  introduction_screen: ^2.1.0
  youtube_player_flutter: ^8.0.0
  faker: ^2.0.0
  #TODO: buradan diğer navbarı sil,

  flutter_vector_icons: ^1.0.0
  cool_alert: ^1.0.3
  flutter_form_builder: "^6.0.0-nullsafety.1"
  getwidget: ^2.0.3
  url_launcher: ^6.0.9
  # geolocator: 7.6.2

  flutter_native_splash: ^1.2.0
  shared_preferences: ^2.0.6
  flutter_staggered_grid_view: ^0.4.0
  video_thumbnail: ^0.4.3
  flutter_image_compress: ^1.0.0-nullsafety
  path_provider: ^2.0.2
  flutter_linkify: ^5.0.2
  flutter_slidable: ^0.6.0
  photo_view: ^0.12.0
  pinch_zoom: ^1.0.0
  cached_network_image: ^3.1.0
  flutter_fortune_wheel:
    git:
      url: https://github.com/ozyildirim/flutter_fortune_wheel
  logger: ^1.0.0
  google_fonts: ^2.1.0
  flutter_bounce: ^1.1.0
  # google_maps_place_picker: ^2.0.0-nullsafety.0
  
  google_maps_flutter: ^2.1.1
  table_calendar: ^3.0.2
  share_plus: ^2.1.4
  just_audio: ^0.9.5
  search_choices: ^2.0.7
  expansion_card: ^0.1.0
  qr_flutter: ^4.0.0
  profanity_filter: ^2.0.0
  circular_menu: ^1.2.3
  awesome_notifications: ^0.6.17
  easy_localization: ^3.0.0
  paginate_firestore: ^1.0.3
  connectivity_plus: ^1.1.0
  package_info_plus: ^1.0.6
  multi_select_flutter: ^4.0.0
  youtube_metadata: ^1.0.1
  flutter_blurhash: ^0.6.0
  permission_handler: ^8.2.6
  google_maps_place_picker_mb: ^2.0.0-mb.9
  google_maps_webservice: ^0.0.20-nullsafety.5
  geolocator: ^7.7.1
  image_cropper: ^1.4.1
  im_stepper: ^0.1.3
  flutter_svg: ^1.0.0
  syncfusion_flutter_pdfviewer: ^19.3.54-beta
  readmore: ^2.1.0
  ntp: ^2.0.0

  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app/logo.png"
  remove_alpha_ios: true


#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/
    - assets/images/application_page/
    - assets/images/app/
    - assets/images/app/interests/
    - assets/images/app/situations/
    - assets/images/onboarding/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Thin.otf
          weight: 100
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Medium.otf
          weight: 400
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Regular.otf
          weight: 500
        - asset: assets/fonts/SanFrancisco/SF-Pro-Display-Bold.otf
          weight: 700
