List<String> eventTypes = [
  "Açık Hava Etkinliği",
  "Kapalı Mekan Etkinliği",
  "Workshop",
];

List<String> eventPlatformTypes = [
  "Fiziksel Etkinlik",
  "Online Etkinlik",
];

List<String> reportReasons = [
  "Telif İhlali",
  "Nefret Söylemi",
  "Çalıntı İçerik",
  "Uygunsuz",
];

List<String> postTypes = [
  "Görüntü",
  "Video",
  "Ses",
];

List<String> artistLabels = [
  "A&R",
  "Aranjör",
  "Beat Maker",
  "Besteci",
  "DJ",
  "Enstrümanist",
  "Kayıt Stüdyo İşletmecisi",
  "Mastering",
  "Menejerlik",
  "Mix",
  "Müzik Aletleri Üreticisi",
  "Müzik Anime ve Manga",
  "Müzik Eleştirmeni",
  "Müzik Gazeteciliği",
  "Müzik Organizasyon",
  "Müzik Öğretmeni",
  "Müzik Tarihçisi",
  "Müzik Teorisyeni",
  "Müzik Yazılımı",
  "Müzikoloğ",
  "Müzis ses sistemleri ve teknolijisi",
  "Orkestra Şefi",
  "Orkestrasyon",
  "Produktör",
  "Ses Mühendisi",
  "Söz Yazarı",
  "Vokal  ",
  "Vokal Koçu",
  "Oyuncu",
  "Senarist",
  "Oyun Yazarı",
  "Suflör",
  "Tiyatro Eleştirmeni",
  "Kostüm Tasarımcısı",
  "Tiyatro Teorisyeni",
  "Makyöz",
  "Sanat Yönetmeni",
  "Figüran",
  "Oyuncu Koçu",
  "Sanat Koleksiyoncusu",
  "Seslendirme Sanatçısı",
  "Televizyon Yönetmeni",
  "Video Oyunu Sanatçısı",
  "Yapım Tasarımcısı",
  "Yaratıcı Yönetmen",
  "Animasyon Film Yapımcısı",
  "Belgesel ve Reklam Fotoğrafçısı",
  "Ses ve Görüntü Yönetmeni",
  "Yardımcı Yönetmen",
  "İkinci Reji",
  "Üçüncü Reji",
  "Görüntü Yönetmeni",
  "Birinci Kamera Asistanı",
  "İkinci Kamera Asistanı",
  "Kamera Prodüksiyon Asistanı",
  "Steadicam Operatörü",
  "Işık Şefi",
  "Birinci Işık Asistanı",
  "Işık Teknisyeni",
  "Kayıt& Miksaj Sorumlusu",
  "Boom Operatörü",
  "Ses Teknisyeni",
  "Kurgucu",
  "Tasarımcı",
];
