List<String> eventTypes = [
  "Açık Hava Etkinliği",
  "Kapalı Mekan Etkinliği",
  "Workshop",
];

List<String> eventPlatformTypes = [
  "Fiziksel Etkinlik",
  "Online Etkinlik",
];

List<String> reportReasons = [
  "Telif İhlali",
  "Nefret Söylemi",
  "Çalıntı İçerik",
  "Uygunsuz",
];

List<String> postTypes = [
  "Görüntü",
  "Video",
  "Ses",
];

List<String> artistLabels = [
  "A&R",
  "Aranjör",
  "Beat Maker",
  "Besteci",
  "DJ",
  "Enstrümanist",
  "Kayıt Stüdyo İşletmecisi",
  "Mastering",
  "Menejerlik",
  "Mix",
  "Müzik Aletleri Üreticisi",
  "Müzik Anime ve Manga",
  "Müzik Eleştirmeni",
  "Müzik Gazeteciliği",
  "Müzik Organizasyon",
  "Müzik Öğretmeni",
  "Müzik Tarihçisi",
  "Müzik Teorisyeni",
  "Müzikoloğ",
  "Müzis ses sistemleri ve teknolijisi",
  "Orkestra Şefi",
  "Orkestra Şef Yardımcısı",
  "Grafiker",
  "Sahne Terzisi",
  "Kast Yönetmeni",
  "Yönetmen Yardımcısı",
  "Orkestrasyon",
  "Produktör",
  "Ses Mühendisi",
  "Aksesuar Sorumlusu",
  "Dekor Şefi",
  "Söz Yazarı",
  "Dublör",
  "Rodi",
  "Tonmaister",
  "Tenor",
  "Soprano",
  "Lirik Tenor",
  "Grafiker",
  "Dekor Teknisyeni",
  "Metin Yazarı",
  "Fotoğrafçı",
  "Film Eleştirmeni",
  "Editör",
  "Kast Yönetmeni",
  "Prodüksiyon Amiri",
  "Kostüm Tasarımcısı",
  "Görsel Efekt Uzmanı",
  "Vokal",
  "Vokal Koçu",
  "Oyuncu",
  "Senarist",
  "Oyun Yazarı",
  "Suflör",
  "Tiyatro Eleştirmeni",
  "Kostüm Tasarımcısı",
  "Tiyatro Teorisyeni",
  "Makyöz",
  "Makyaj Sorumlusu",
  "Set Kuaförü",
  "Kamera Sorumlusu",
  "Set Amiri",
  "Set Asistanı",
  "Özel Efekt Tasarımcısı",
  "Post Produksiyon Sorumlusu",
  "Sanat Yönetmeni",
  "Figüran",
  "Oyuncu Koçu",
  "Sanat Koleksiyoncusu",
  "Seslendirme Sanatçısı",
  "Televizyon Yönetmeni",
  "Video Oyunu Sanatçısı",
  "Yapım Tasarımcısı",
  "Ses ve Işık Yöneticisi",
  "Bariton",
  "Yaratıcı Yönetmen",
  "Animasyon Film Yapımcısı",
  "Belgesel ve Reklam Fotoğrafçısı",
  "Ses ve Görüntü Yönetmeni",
  "Yardımcı Yönetmen",
  "İkinci Reji",
  "Üçüncü Reji",
  "Görüntü Yönetmeni",
  "Kamera Asistanı",
  "Kamera Prodüksiyon Asistanı",
  "Steadicam Operatörü",
  "Işık Şefi",
  "Birinci Işık Asistanı",
  "Işık Teknisyeni",
  "Kayıt& Miksaj Sorumlusu",
  "Boom Operatörü",
  "Ses Teknisyeni",
  "Kurgu Yönetmeni",
  "Tasarımcı",
  "Takı Tasarımcısı",
  "Sanat Koleksiyoncusu",
  "Sanat Terapisti",
  "Model",
  "Ressam",
  "Heykeltıraş",
  "Yazar",
  "Alto",
  "Diyalog Yazarı",
  "Animasyon Tasarımcısı",
  "Dijital Tasarım Uzmanı",
  "Radyo Program Yapımcısı",
  "Radyo Teknik Yönetmeni",
  "Radyo Haber Spikeri",
  "Radyo Metin Yazarı"
];
